apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.ldkube.com
spec:
  group: ldkube.com
  names:
    kind: Application
    plural: applications
    singular: application
    shortNames:
    - app
    - ap
    - a
  scope: Namespaced
  versions: 
  - name: v1
    served: true
    storage: true
    schema: 
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties: 
              port:
                type: integer
              replicas:
                type: integer
              containerName:
                type: string
              containerTag:
                type: string