apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {namespace}
  name: {name}-deployment
  labels:
    app: {name}
spec:
  replicas: {replicas}
  selector:
    matchLabels:
      app: {name}
  template:
    metadata:
      labels:
        app: {name}
    spec:
      containers:
        - name: {name}
          image: {container_name}:{container_tag}
          ports:
            - containerPort: 80